services:
  postgres:
    image: postgres:16-alpine
    container_name: devshowcase-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=devshowcase
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devshowcase-network

  redis:
    image: redis:7-alpine
    container_name: devshowcase-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devshowcase-network

  mailpit:
    image: axllent/mailpit:latest
    container_name: devshowcase-mailpit
    ports:
      - '1025:1025'
      - '8025:8025'
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1
    networks:
      - devshowcase-network

volumes:
  postgres-data:
  redis-data:

networks:
  devshowcase-network:
    driver: bridge

